# Generated by Django 3.0.3 on 2021-01-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='scan',
            field=models.ImageField(upload_to='', verbose_name='SCAN'),
        ),
    ]
