# Generated by Django 3.0.3 on 2021-01-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20210114_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='description',
            field=models.CharField(default='Nothing', max_length=550, verbose_name='DESCRIPTION'),
        ),
    ]
